// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrZFB8yQOESUT7q2Bm2ARtI9kQ34KrEwg',
    appId: '1:843078322062:web:4986be05fb82bf12b686df',
    messagingSenderId: '843078322062',
    projectId: 'albuhairaalarabia2026',
    authDomain: 'albuhairaalarabia2026.firebaseapp.com',
    storageBucket: 'albuhairaalarabia2026.firebasestorage.app',
    measurementId: 'G-87D3N9N43R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBv4UoP6mT2XGsXd3cT9wULDpP-PX7YGA',
    appId: '1:843078322062:android:1634bddd9b5fde20b686df',
    messagingSenderId: '843078322062',
    projectId: 'albuhairaalarabia2026',
    storageBucket: 'albuhairaalarabia2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH-pW2B9_C5xRAimhUPKwey2BTH4q3_TQ',
    appId: '1:843078322062:ios:64ffa7f80dc4b4d4b686df',
    messagingSenderId: '843078322062',
    projectId: 'albuhairaalarabia2026',
    storageBucket: 'albuhairaalarabia2026.firebasestorage.app',
    iosBundleId: 'com.albuhaira.nipras',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH-pW2B9_C5xRAimhUPKwey2BTH4q3_TQ',
    appId: '1:843078322062:ios:cd70a5581a467784b686df',
    messagingSenderId: '843078322062',
    projectId: 'albuhairaalarabia2026',
    storageBucket: 'albuhairaalarabia2026.firebasestorage.app',
    iosBundleId: 'com.example.orderTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrZFB8yQOESUT7q2Bm2ARtI9kQ34KrEwg',
    appId: '1:843078322062:web:5e3781a4299c8abab686df',
    messagingSenderId: '843078322062',
    projectId: 'albuhairaalarabia2026',
    authDomain: 'albuhairaalarabia2026.firebaseapp.com',
    storageBucket: 'albuhairaalarabia2026.firebasestorage.app',
    measurementId: 'G-93MLWLNC5V',
  );
}
