// Arabic text normalization helpers (no extra dependencies).
//
// Syncfusion PDF text extraction can return Arabic Presentation Forms-B
// characters (FE70–FEFF). These code points look like normal Arabic letters
// but won't match regular Arabic strings/regexes. We map them to their NFKC
// equivalents first, then the caller can apply normal Arabic cleanup.

const Map<int, String> _arabicPresentationFormBToNfkc = <int, String>{
  0xFE70: ' ً',
  0xFE71: 'ـً',
  0xFE72: ' ٌ',
  0xFE74: ' ٍ',
  0xFE76: ' َ',
  0xFE77: 'ـَ',
  0xFE78: ' ُ',
  0xFE79: 'ـُ',
  0xFE7A: ' ِ',
  0xFE7B: 'ـِ',
  0xFE7C: ' ّ',
  0xFE7D: 'ـّ',
  0xFE7E: ' ْ',
  0xFE7F: 'ـْ',
  0xFE80: 'ء',
  0xFE81: 'آ',
  0xFE82: 'آ',
  0xFE83: 'أ',
  0xFE84: 'أ',
  0xFE85: 'ؤ',
  0xFE86: 'ؤ',
  0xFE87: 'إ',
  0xFE88: 'إ',
  0xFE89: 'ئ',
  0xFE8A: 'ئ',
  0xFE8B: 'ئ',
  0xFE8C: 'ئ',
  0xFE8D: 'ا',
  0xFE8E: 'ا',
  0xFE8F: 'ب',
  0xFE90: 'ب',
  0xFE91: 'ب',
  0xFE92: 'ب',
  0xFE93: 'ة',
  0xFE94: 'ة',
  0xFE95: 'ت',
  0xFE96: 'ت',
  0xFE97: 'ت',
  0xFE98: 'ت',
  0xFE99: 'ث',
  0xFE9A: 'ث',
  0xFE9B: 'ث',
  0xFE9C: 'ث',
  0xFE9D: 'ج',
  0xFE9E: 'ج',
  0xFE9F: 'ج',
  0xFEA0: 'ج',
  0xFEA1: 'ح',
  0xFEA2: 'ح',
  0xFEA3: 'ح',
  0xFEA4: 'ح',
  0xFEA5: 'خ',
  0xFEA6: 'خ',
  0xFEA7: 'خ',
  0xFEA8: 'خ',
  0xFEA9: 'د',
  0xFEAA: 'د',
  0xFEAB: 'ذ',
  0xFEAC: 'ذ',
  0xFEAD: 'ر',
  0xFEAE: 'ر',
  0xFEAF: 'ز',
  0xFEB0: 'ز',
  0xFEB1: 'س',
  0xFEB2: 'س',
  0xFEB3: 'س',
  0xFEB4: 'س',
  0xFEB5: 'ش',
  0xFEB6: 'ش',
  0xFEB7: 'ش',
  0xFEB8: 'ش',
  0xFEB9: 'ص',
  0xFEBA: 'ص',
  0xFEBB: 'ص',
  0xFEBC: 'ص',
  0xFEBD: 'ض',
  0xFEBE: 'ض',
  0xFEBF: 'ض',
  0xFEC0: 'ض',
  0xFEC1: 'ط',
  0xFEC2: 'ط',
  0xFEC3: 'ط',
  0xFEC4: 'ط',
  0xFEC5: 'ظ',
  0xFEC6: 'ظ',
  0xFEC7: 'ظ',
  0xFEC8: 'ظ',
  0xFEC9: 'ع',
  0xFECA: 'ع',
  0xFECB: 'ع',
  0xFECC: 'ع',
  0xFECD: 'غ',
  0xFECE: 'غ',
  0xFECF: 'غ',
  0xFED0: 'غ',
  0xFED1: 'ف',
  0xFED2: 'ف',
  0xFED3: 'ف',
  0xFED4: 'ف',
  0xFED5: 'ق',
  0xFED6: 'ق',
  0xFED7: 'ق',
  0xFED8: 'ق',
  0xFED9: 'ك',
  0xFEDA: 'ك',
  0xFEDB: 'ك',
  0xFEDC: 'ك',
  0xFEDD: 'ل',
  0xFEDE: 'ل',
  0xFEDF: 'ل',
  0xFEE0: 'ل',
  0xFEE1: 'م',
  0xFEE2: 'م',
  0xFEE3: 'م',
  0xFEE4: 'م',
  0xFEE5: 'ن',
  0xFEE6: 'ن',
  0xFEE7: 'ن',
  0xFEE8: 'ن',
  0xFEE9: 'ه',
  0xFEEA: 'ه',
  0xFEEB: 'ه',
  0xFEEC: 'ه',
  0xFEED: 'و',
  0xFEEE: 'و',
  0xFEEF: 'ى',
  0xFEF0: 'ى',
  0xFEF1: 'ي',
  0xFEF2: 'ي',
  0xFEF3: 'ي',
  0xFEF4: 'ي',
  0xFEF5: 'لآ',
  0xFEF6: 'لآ',
  0xFEF7: 'لأ',
  0xFEF8: 'لأ',
  0xFEF9: 'لإ',
  0xFEFA: 'لإ',
  0xFEFB: 'لا',
  0xFEFC: 'لا',
};

String nfkcArabicPresentationForms(String input) {
  if (input.isEmpty) return input;
  final buffer = StringBuffer();
  for (final rune in input.runes) {
    final replacement = _arabicPresentationFormBToNfkc[rune];
    if (replacement != null) {
      buffer.write(replacement);
    } else {
      buffer.writeCharCode(rune);
    }
  }
  return buffer.toString();
}
